### ISSUE TITLE
Перенести stylus и верстку на основе em и частичного reset'а из node-blog. 

### ISSUE THREAD

**Issue by A** [A/shuvalov.info#11]
Не мешало бы еще почитать об `em`'ах и возможных проблемах с ними.

**Comment by A** [comment]
Может быть вообще, вынести верстку в отдельную тему?

**Comment by iamstarkov** [comment]
а зачем верстать в `em`?

**Comment by A** [comment]
Это был намек на `rem`? =)

**Comment by iamstarkov** [comment]
необязательно, но я правда непонимаю зачем верстать на емах, поэтому и спросил

**Comment by A** [comment]
Ну я проникся тем, что можно задать на body базовый размер, относительно которого будет размер текста/заголовков, полей, отступов и всего, что с этим связано. А если что, можно изменить базовый размер, и все само подстроится под это.

**Comment by A** [comment]
Но я особо не практиковал такой подход, по этому хочу попробовать скорее из интереса. Вот здесь, вроде бы ок получилось: https://github.com/shuvalov-anton/Patterns-For-Large-Scale-JavaScript-Application-Architecture/blob/gh-pages/_stylus/main.styl

**Comment by iamstarkov** [comment]
на ремах удобнее, нет головной боли с вложенностью

**Comment by A** [comment]
Да, я наверное, все-таки в них сделаю. У меня еще партак с тегом `<small>` вышел, `lh` остается от `<h3>`, и строка ломается, но, в целом, мне кажется, что там верстка по-лучше получилась, чем в блоге.
