### ISSUE TITLE
прямая ссылка на github edit

### ISSUE THREAD

**Issue by iamstarkov** [A/shuvalov.info#24]
добавь ссылку на прямое редактирование на гитхабе, чтобы можно было быстрее и удобнее править ошибки и опечатки

**Comment by A** [comment]
Хорошая идея :) Займусь этим, чуть позже, спасибо!

**Comment by iamstarkov** [comment]
> Займусь этим, чуть позже

ахаха

**Comment by A** [comment]
as I planned :D

**Comment by A** [comment]
Мне кажется, что ценность ссылки на prose.io или конкретные посты на gh переоценена. А вот на репо можно и добавить

**Comment by iamstarkov** [comment]
ценность прозио точно переоценена, так как прозио не работает

**Comment by iamstarkov** [comment]
а ссылки в постах edit-on-github позволят тебе самому и другим людям тоже исправлять ошибки, когда вычитываешь или просто читаешь на сайте

**Comment by iamstarkov** [comment]
например мне два дня назад прислали пулл-реквест таким образом iamstarkov/iamstarkov.github.io#11

**Comment by iamstarkov** [comment]
ну окай
